In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Testing_Data.csv")

In [3]:
data=pd.read_csv("Training_Data.csv")

In [4]:
df.head()


Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             NaN         Urban  
4             1.0         Urban

In [5]:
x_train=data.iloc[:,:-1]

In [6]:
y_train=data.iloc[:,-1]

In [7]:
y_train

0      Y
1      N
2      Y
3      Y
4      Y
      ..
609    Y
610    Y
611    Y
612    Y
613    N
Name: Loan_Status, Length: 614, dtype: object

In [8]:
#handling missing data
from sklearn.impute import SimpleImputer
imp_mean=SimpleImputer(missing_values=np.nan,strategy='mean')

In [9]:
numeric_columns=list(np.where((x_train.dtypes==np.int64) | (x_train.dtypes==np.float64))[0])

In [10]:
credit_score=numeric_columns[4:5]

In [11]:
credit_score

[10]

In [12]:
numeric_columns=numeric_columns[:4]

In [13]:
numeric_columns

[6, 7, 8, 9]

In [14]:
x_train.iloc[:,numeric_columns]

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term
0               5849                0.0         NaN             360.0
1               4583             1508.0       128.0             360.0
2               3000                0.0        66.0             360.0
3               2583             2358.0       120.0             360.0
4               6000                0.0       141.0             360.0
..               ...                ...         ...               ...
609             2900                0.0        71.0             360.0
610             4106                0.0        40.0             180.0
611             8072              240.0       253.0             360.0
612             7583                0.0       187.0             360.0
613             4583                0.0       133.0             360.0

[614 rows x 4 columns]

In [15]:
imp_mean.fit(x_train.iloc[:,numeric_columns])

SimpleImputer()

In [16]:
x_train.iloc[:,numeric_columns]=imp_mean.transform(x_train.iloc[:,numeric_columns])

In [17]:
string_columns=list(np.where((x_train.dtypes==np.object))[0])


C:\Users\KIIT\AppData\Local\Temp\ipykernel_21352\466058247.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  string_columns=list(np.where((x_train.dtypes==np.object))[0])


In [18]:
numeric_columns

[6, 7, 8, 9]

In [19]:
numeric_columns=numeric_columns[:4]

In [20]:
numeric_columns

[6, 7, 8, 9]

In [21]:
string_columns

[0, 1, 2, 3, 4, 5, 11]

In [22]:
imp_mean=SimpleImputer(missing_values=np.nan,strategy='most_frequent')


In [23]:
imp_mean.fit(x_train.iloc[:,string_columns])

SimpleImputer(strategy='most_frequent')

In [24]:
x_train.iloc[:,string_columns]=imp_mean.transform(x_train.iloc[:,string_columns])

In [25]:
imp_mean.fit(x_train.iloc[:,credit_score])

SimpleImputer(strategy='most_frequent')

In [26]:
x_train.iloc[:,credit_score]=imp_mean.transform(x_train.iloc[:,credit_score])

In [27]:
x_train.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [28]:
#missing data handled

In [29]:
y_train.isnull().sum()

0

In [30]:
 #encoding the data
    

In [31]:
def labelencodermethod(series):
    from sklearn import preprocessing
    le=preprocessing.LabelEncoder()
    le.fit(series)
    return le.transform(series)

In [32]:
y_train=labelencodermethod(y_train)

In [33]:
y_train

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,

In [34]:
x_train=x_train.drop("Loan_ID",axis=1)

In [35]:
col_0=x_train.columns[0]

In [36]:
x_train[col_0]=labelencodermethod(x_train[col_0])

In [37]:
col_1=x_train.columns[1]

In [38]:
x_train[col_1]=labelencodermethod(x_train[col_1])

In [39]:
col_2=x_train.columns[2]

In [40]:
x_train[col_2]=labelencodermethod(x_train[col_2])

In [41]:
col_3=x_train.columns[3]

In [42]:
x_train[col_3]=labelencodermethod(x_train[col_3])

In [43]:
col_4=x_train.columns[4]

In [44]:
x_train[col_4]=labelencodermethod(x_train[col_4])

In [45]:
col_10=x_train.columns[10]
x_train[col_10]=labelencodermethod(x_train[col_10])

In [46]:
x_train

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0         1        0           0          0              0           5849.0   
1         1        1           1          0              0           4583.0   
2         1        1           0          0              1           3000.0   
3         1        1           0          1              0           2583.0   
4         1        0           0          0              0           6000.0   
..      ...      ...         ...        ...            ...              ...   
609       0        0           0          0              0           2900.0   
610       1        1           3          0              0           4106.0   
611       1        1           1          0              0           8072.0   
612       1        1           2          0              0           7583.0   
613       0        0           0          0              1           4583.0   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0  146.412162             360.0             1.0   
1               1508.0  128.000000             360.0             1.0   
2                  0.0   66.000000             360.0             1.0   
3               2358.0  120.000000             360.0             1.0   
4                  0.0  141.000000             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0   71.000000             360.0             1.0   
610                0.0   40.000000             180.0             1.0   
611              240.0  253.000000             360.0             1.0   
612                0.0  187.000000             360.0             1.0   
613                0.0  133.000000             360.0             0.0   

     Property_Area  
0                2  
1                0  
2                2  
3                2  
4                2  
..             ...  
609              0  
610              0  
611              2  
612              2  
613              1  

[614 rows x 11 columns]

In [47]:
y_train

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,

In [48]:
from sklearn.model_selection import train_test_split
x_train1,x_test1,y_train1,y_test1=train_test_split(x_train,y_train,test_size=0.3,random_state=2)

In [49]:
x_test=df.iloc[:,:]

In [50]:
x_test

Loan_ID Gender Married Dependents     Education Self_Employed  \
0    LP001015   Male     Yes          0      Graduate            No   
1    LP001022   Male     Yes          1      Graduate            No   
2    LP001031   Male     Yes          2      Graduate            No   
3    LP001035   Male     Yes          2      Graduate            No   
4    LP001051   Male      No          0  Not Graduate            No   
..        ...    ...     ...        ...           ...           ...   
362  LP002971   Male     Yes         3+  Not Graduate           Yes   
363  LP002975   Male     Yes          0      Graduate            No   
364  LP002980   Male      No          0      Graduate            No   
365  LP002986   Male     Yes          0      Graduate            No   
366  LP002989   Male      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5720                  0       110.0             360.0   
1               3076               1500       126.0             360.0   
2               5000               1800       208.0             360.0   
3               2340               2546       100.0             360.0   
4               3276                  0        78.0             360.0   
..               ...                ...         ...               ...   
362             4009               1777       113.0             360.0   
363             4158                709       115.0             360.0   
364             3250               1993       126.0             360.0   
365             5000               2393       158.0             360.0   
366             9200                  0        98.0             180.0   

     Credit_History Property_Area  
0               1.0         Urban  
1               1.0         Urban  
2               1.0         Urban  
3               NaN         Urban  
4               1.0         Urban  
..              ...           ...  
362             1.0         Urban  
363             1.0         Urban  
364             NaN     Semiurban  
365             1.0         Rural  
366             1.0         Rural  

[367 rows x 12 columns]

In [51]:

numeric_columns

[6, 7, 8, 9]

In [52]:
credit_score

[10]

In [53]:
imp_mean=SimpleImputer(missing_values=np.nan,strategy='mean')

In [54]:
imp_mean.fit(x_test.iloc[:,numeric_columns])
#x_test.iloc[:,numeric_columns]=imp_mean.transform(x_test.iloc[:,numeric_columns])

SimpleImputer()

In [55]:
x_test.iloc[:,numeric_columns]=imp_mean.transform(x_test.iloc[:,numeric_columns])

In [56]:
imp_mean=SimpleImputer(missing_values=np.nan,strategy='most_frequent')

In [57]:
imp_mean.fit(x_test.iloc[:,string_columns])

SimpleImputer(strategy='most_frequent')

In [58]:
x_test.iloc[:,string_columns]=imp_mean.transform(x_test.iloc[:,string_columns])

In [59]:
imp_mean.fit(x_test.iloc[:,credit_score])

SimpleImputer(strategy='most_frequent')

In [60]:
x_test.iloc[:,credit_score]=imp_mean.transform(x_test.iloc[:,credit_score])

In [61]:
x_test.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [62]:
x_test=x_test.drop("Loan_ID",axis=1)

In [63]:


col_0=x_test.columns[0]
x_test[col_0]=labelencodermethod(x_test[col_0])
col_1=x_test.columns[1]
x_test[col_1]=labelencodermethod(x_test[col_1])
col_2=x_test.columns[2]
x_test[col_2]=labelencodermethod(x_test[col_2])
col_3=x_test.columns[3]
x_test[col_3]=labelencodermethod(x_test[col_3])
col_4=x_test.columns[4]
x_test[col_4]=labelencodermethod(x_test[col_4])



In [64]:
col_10=x_test.columns[10]
x_test[col_10]=labelencodermethod(x_test[col_10])



In [65]:
x_test

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0         1        1           0          0              0           5720.0   
1         1        1           1          0              0           3076.0   
2         1        1           2          0              0           5000.0   
3         1        1           2          0              0           2340.0   
4         1        0           0          1              0           3276.0   
..      ...      ...         ...        ...            ...              ...   
362       1        1           3          1              1           4009.0   
363       1        1           0          0              0           4158.0   
364       1        0           0          0              0           3250.0   
365       1        1           0          0              0           5000.0   
366       1        0           0          0              1           9200.0   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0       110.0             360.0             1.0   
1               1500.0       126.0             360.0             1.0   
2               1800.0       208.0             360.0             1.0   
3               2546.0       100.0             360.0             1.0   
4                  0.0        78.0             360.0             1.0   
..                 ...         ...               ...             ...   
362             1777.0       113.0             360.0             1.0   
363              709.0       115.0             360.0             1.0   
364             1993.0       126.0             360.0             1.0   
365             2393.0       158.0             360.0             1.0   
366                0.0        98.0             180.0             1.0   

     Property_Area  
0                2  
1                2  
2                2  
3                2  
4                2  
..             ...  
362              2  
363              2  
364              1  
365              0  
366              0  

[367 rows x 11 columns]

In [66]:
#linear regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [67]:
y_pred

array([ 8.69763510e-01,  8.52294334e-01,  8.32219939e-01,  8.54211102e-01,
        7.16501764e-01,  7.51197842e-01,  7.27016196e-01,  6.76441444e-02,
        8.51220186e-01,  6.63357418e-01,  7.12685978e-01,  8.26342926e-01,
        8.30666445e-01,  1.50475662e-01,  7.70044557e-01,  7.74350972e-01,
        8.22710613e-01,  8.62338264e-01,  7.34974180e-01,  7.42964190e-01,
        8.07676507e-01,  7.80701493e-01,  7.75855776e-01,  7.17145127e-01,
        7.70177872e-01, -2.23800161e-01,  8.57668786e-01,  7.83445745e-01,
        8.61085796e-01,  7.62366660e-01,  7.16839397e-01,  8.48464871e-01,
        7.28526098e-01,  8.24293408e-01,  8.53411820e-01,  3.17725308e-02,
        8.38056460e-01,  8.42059387e-01,  7.72121700e-01,  7.44248688e-01,
        8.64272097e-01,  7.87131068e-01,  7.71116799e-01,  7.08142716e-01,
        7.94988227e-01,  8.07379061e-01,  7.71655532e-01,  6.72946360e-01,
        7.20636875e-01,  7.82481006e-01,  8.50058090e-01,  7.93100423e-01,
        8.12329364e-01,  

In [68]:
#linear regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
model=LinearRegression()
model.fit(x_train1,y_train1)
y_pred=model.predict(x_test1)
r2_score(y_test1,y_pred)

0.23976765837369607

In [69]:
#Polynomial_Regression
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
model=LinearRegression()
poly=PolynomialFeatures(degree=2)
x_train_poly=poly.fit_transform(x_train)
model.fit(x_train_poly,y_train)
x_test_poly=poly.fit_transform(x_test)
y_pred=model.predict(x_test_poly)

In [70]:
y_pred

array([ 0.82305087,  0.79255058,  0.77072307,  0.81982687,  0.60816919,
        0.7756001 ,  0.78190302, -0.10756372,  1.02720656,  0.88033665,
        0.58790174,  0.88205558,  1.03728411,  0.21039928,  0.81203498,
        0.66442818,  0.78428273,  0.93108454,  0.68313125,  0.93632635,
        0.85879559,  0.59477143,  0.68353503,  0.81955646,  0.78035996,
       -0.50882611,  0.80715955,  0.76398866,  0.95685049,  0.80248114,
        0.85549651,  0.79482092,  0.8462721 ,  0.8308293 ,  0.84842691,
        0.25226713,  0.95039308,  0.75971362,  0.55189361,  0.7195091 ,
        0.84535776,  0.77075749,  0.945104  ,  0.78913956,  0.78050114,
        0.83238375,  0.81567461,  0.85036471,  0.74647067,  0.92544713,
        0.78728302,  0.8560781 ,  0.88177769,  1.12678588,  0.66225701,
        0.02964928,  0.62210232,  0.90975087, -0.0319759 ,  1.11185745,
        0.91189019,  0.83944639,  0.69094662,  0.08894698,  0.75853086,
        0.92924758,  0.01708675,  0.10756658,  0.83068065, -0.00

In [71]:
#Polynomial_Regression
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
model=LinearRegression()
poly=PolynomialFeatures(degree=2)
x_train1_poly=poly.fit_transform(x_train1)
model.fit(x_train1_poly,y_train1)
x_test1_poly=poly.fit_transform(x_test1)
y_pred=model.predict(x_test1_poly)
r2_score(y_test1,y_pred)

-0.42572241122263144

In [72]:
#decision_tree
from sklearn.tree import DecisionTreeRegressor
model=DecisionTreeRegressor(max_depth=4)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)


In [73]:
y_pred

array([0.87555556, 0.87555556, 0.75694444, 0.87555556, 0.87555556,
       0.75694444, 0.87555556, 0.01851852, 0.75694444, 0.87555556,
       0.87555556, 0.75694444, 0.87555556, 0.125     , 0.87555556,
       0.87555556, 0.75694444, 0.87555556, 0.75694444, 0.87555556,
       0.87555556, 0.87555556, 0.87555556, 0.87555556, 0.75694444,
       1.        , 0.75694444, 0.75694444, 0.87555556, 0.87555556,
       0.87555556, 0.75694444, 0.75694444, 0.75694444, 0.87555556,
       0.01851852, 0.75694444, 0.87555556, 0.87555556, 0.75694444,
       0.87555556, 0.87555556, 0.87555556, 0.75694444, 0.87555556,
       0.75694444, 0.75694444, 0.87555556, 0.75694444, 0.75694444,
       0.87555556, 0.87555556, 0.75694444, 0.87555556, 0.87555556,
       0.01851852, 0.74100719, 0.87555556, 0.01851852, 0.87555556,
       0.87555556, 0.87555556, 0.75694444, 0.01851852, 0.87555556,
       0.75694444, 0.125     , 0.01851852, 0.75694444, 0.01851852,
       0.87555556, 0.87555556, 0.75694444, 0.74100719, 0.75694

In [74]:
#decision_tree
from sklearn.tree import DecisionTreeRegressor
model=DecisionTreeRegressor(max_depth=4)
model.fit(x_train1,y_train1)
y_pred=model.predict(x_test1)
r2_score(y_test1,y_pred)

0.15184593396058266

In [75]:
#Random_Forest
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(n_estimators=25,random_state=10)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [76]:
y_pred

array([0.92, 1.  , 0.88, 1.  , 0.68, 0.64, 0.8 , 0.  , 0.96, 0.96, 0.8 ,
       0.8 , 0.92, 0.28, 0.92, 0.92, 0.76, 1.  , 0.64, 0.68, 0.96, 0.6 ,
       0.92, 0.84, 0.52, 0.72, 0.8 , 0.48, 0.8 , 0.88, 0.8 , 0.88, 0.76,
       0.76, 1.  , 0.12, 0.84, 0.88, 0.96, 0.76, 0.88, 0.96, 1.  , 0.56,
       0.72, 0.68, 0.56, 0.96, 0.68, 0.68, 1.  , 0.96, 0.92, 0.92, 0.52,
       0.12, 0.96, 0.92, 0.  , 0.64, 1.  , 1.  , 0.72, 0.04, 0.68, 0.96,
       0.12, 0.08, 0.88, 0.12, 0.96, 0.76, 0.64, 0.64, 0.76, 0.88, 0.8 ,
       0.88, 0.84, 0.72, 0.4 , 0.88, 0.  , 0.72, 0.28, 0.6 , 0.84, 0.92,
       0.92, 0.6 , 0.88, 0.92, 0.76, 0.84, 0.08, 0.6 , 0.84, 0.96, 0.72,
       0.88, 0.96, 0.  , 1.  , 0.52, 0.96, 0.72, 0.  , 0.56, 0.88, 0.68,
       0.68, 0.88, 0.64, 0.96, 0.8 , 0.8 , 0.4 , 0.12, 0.04, 0.04, 0.88,
       0.92, 0.8 , 0.32, 0.  , 0.88, 0.  , 0.96, 0.8 , 1.  , 0.96, 0.24,
       0.84, 0.76, 0.56, 0.96, 0.72, 0.56, 0.92, 1.  , 0.24, 0.84, 0.12,
       0.72, 0.72, 0.76, 0.88, 0.12, 0.92, 0.84, 0.

In [77]:
#Random_Forest
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(n_estimators=25,random_state=10)
model.fit(x_train1,y_train1)
y_pred=model.predict(x_test1)
r2_score(y_test1,y_pred)

0.2092066250339396

In [78]:
#AdaBoost
from sklearn.ensemble  import AdaBoostRegressor
model=AdaBoostRegressor(random_state=0,n_estimators=100)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [79]:
y_pred

array([0.72479564, 0.82536383, 0.70901639, 0.82536383, 0.72479564,
       0.70901639, 0.72479564, 0.        , 0.62264151, 0.82536383,
       0.72479564, 0.70901639, 0.72479564, 0.16666667, 0.72479564,
       0.72479564, 0.70901639, 0.72479564, 0.69852941, 0.71875   ,
       0.82536383, 0.72479564, 0.72479564, 0.72479564, 0.70901639,
       0.0952381 , 0.70901639, 0.70901639, 0.82536383, 0.82536383,
       0.72479564, 0.70901639, 0.69852941, 0.70901639, 0.82536383,
       0.0952381 , 0.70901639, 0.82536383, 0.72479564, 0.69852941,
       0.82536383, 0.72479564, 0.82536383, 0.69852941, 0.72479564,
       0.70901639, 0.70901639, 0.82536383, 0.69852941, 0.71518987,
       0.82536383, 0.82536383, 0.70901639, 0.82536383, 0.72479564,
       0.0952381 , 0.71518987, 0.82536383, 0.06779661, 0.72479564,
       0.82536383, 0.72479564, 0.71518987, 0.        , 0.72479564,
       0.70901639, 0.        , 0.        , 0.71518987, 0.06779661,
       0.72479564, 0.72479564, 0.70901639, 0.69852941, 0.70901

In [80]:
#AdaBoost
from sklearn.ensemble  import AdaBoostRegressor
model=AdaBoostRegressor(random_state=0,n_estimators=100)
model.fit(x_train1,y_train1)
y_pred=model.predict(x_test1)
r2_score(y_test1,y_pred)

0.2526205324512927

In [81]:
 
pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [82]:
#XGBOOST
import xgboost as xgb
model=xgb.XGBRegressor(
    n_estimators=100,
    reg_lambda=1,
    gamma=0,
    max_depth=3,
    learning_rate=0.05   
)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)


In [83]:
y_pred

array([ 0.82430685,  0.9016144 ,  0.7902868 ,  0.881788  ,  0.7432875 ,
        0.7684514 ,  0.7933955 ,  0.04705422,  0.8152517 ,  0.87778986,
        0.785792  ,  0.8168333 ,  0.86118454,  0.20383556,  0.8222748 ,
        0.8145    ,  0.7786221 ,  0.8887361 ,  0.77817744,  0.7240094 ,
        0.91885364,  0.7737355 ,  0.7852069 ,  0.788437  ,  0.751218  ,
        0.32792494,  0.82222164,  0.751218  ,  0.9248859 ,  0.8587521 ,
        0.7660248 ,  0.79540694,  0.8162146 ,  0.8388742 ,  0.88451695,
        0.08375267,  0.8065188 ,  0.87286556,  0.80793744,  0.79399824,
        0.8382437 ,  0.79024523,  0.90541935,  0.696223  ,  0.7439039 ,
        0.76969963,  0.7454295 ,  0.84939086,  0.75975454,  0.7418628 ,
        0.8903262 ,  0.8464952 ,  0.80250216,  0.9136266 ,  0.8003628 ,
        0.093723  ,  0.7342055 ,  0.84495896,  0.11181303,  0.84252834,
        0.90355474,  0.8576711 ,  0.7153367 ,  0.10340335,  0.8179002 ,
        0.88916767,  0.21991724,  0.09137131,  0.8078879 ,  0.09

In [84]:
#XGBOOST
import xgboost as xgb
model=xgb.XGBRegressor(
    n_estimators=100,
    reg_lambda=1,
    gamma=0,
    max_depth=3,
    learning_rate=0.05   
)
model.fit(x_train1,y_train1)
y_pred=model.predict(x_test1)
r2_score(y_test1,y_pred)

0.2267393917536893

In [85]:
#SUPPORT_VECTOR_MACHINE
from sklearn.svm import SVR
model=SVR()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [86]:
y_pred

array([0.89978608, 0.90006931, 0.89972527, 0.89985099, 0.9000437 ,
       0.89984302, 0.89884177, 0.9000865 , 0.90031976, 0.89979057,
       0.89991235, 0.89996169, 0.90023551, 0.90050694, 0.9000384 ,
       0.89979491, 0.89991819, 0.90033868, 0.76854501, 0.8998874 ,
       0.90022828, 0.89854577, 0.90015869, 0.90011304, 0.9019902 ,
       0.46560986, 0.90000925, 0.8942621 , 0.90043472, 0.89946164,
       0.89926029, 0.90002841, 0.89984665, 0.89950802, 0.90016676,
       0.89976792, 0.89491405, 0.89988389, 0.89976266, 0.89967021,
       0.90011225, 0.90011779, 0.90006139, 0.89964197, 0.90015986,
       0.90111633, 0.89985071, 0.9000321 , 0.8989337 , 0.89986202,
       0.90005351, 0.90035997, 0.89962183, 0.90031687, 0.89989283,
       0.89950727, 0.90008303, 0.90000055, 0.89988462, 0.90011233,
       0.90009195, 0.89988166, 0.89990655, 0.90011987, 0.90007247,
       0.89997319, 0.90001868, 0.90002516, 0.89977111, 0.90174863,
       0.90000237, 0.90012783, 0.89951086, 0.89934832, 0.90105

In [87]:
#SUPPORT_VECTOR_MACHINE
from sklearn.svm import SVR
model=SVR()
model.fit(x_train1,y_train1)
y_pred=model.predict(x_test1)
r2_score(y_test1,y_pred)

-0.18969352451247468

In [88]:
from sklearn import preprocessing
from sklearn.feature_selection import SelectKBest, chi2

In [89]:
sc=preprocessing.StandardScaler(with_mean=False)
sc.fit(x_train1)
x_train1=sc.transform(x_train1)
sc.fit(x_test1)
x_test1=sc.transform(x_test1)

In [90]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
knnClassifier=KNeighborsClassifier(n_neighbors=8)
knnClassifier.fit(x_train,y_train)
y_pred=knnClassifier.predict(x_test)


In [91]:
y_pred

array([1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,

In [92]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
knnClassifier=KNeighborsClassifier(n_neighbors=8)
knnClassifier.fit(x_train1,y_train1)
y_pred=knnClassifier.predict(x_test1)
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test1)

0.8108108108108109

In [93]:
#this dataset has been evaluated using different type of regressions and classification techniques,
#thus if we are provided with y_test we can find the r2 score of the model which can be used to find,
#put the accuracy of the model.

In [94]:
#LogicticReression
from sklearn.linear_model import LogisticRegression
LRM=LogisticRegression(random_state=1,max_iter=500)
LRM.fit(x_train,y_train)
y_pred=LRM.predict(x_test)


In [95]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,

In [96]:
#LogicticReression
from sklearn.linear_model import LogisticRegression
LRM=LogisticRegression(random_state=1,max_iter=500)
LRM.fit(x_train1,y_train1)
y_pred=LRM.predict(x_test1)
accuracy_score(y_pred,y_test1)

0.8

In [97]:
male=data[data['Gender']=='Male'].shape[0]

In [98]:
#as we have 489 rows we know there are 489 males

In [99]:

female=data[data['Gender']=='Female'].shape[0]

In [100]:
#as we have 112 rows we know there are 112 females

In [101]:
#1
ratio=female/male
print(ratio)

0.22903885480572597


In [102]:
#2
married_males=len(data.loc[((data['Married'] == 'Yes') & (data['Gender'] == 'Male'))])
print("Married males are:")
print(married_males)
unmarried_males=len(data.loc[((data['Married'] == 'No') & (data['Gender'] == 'Male'))])
print("UnMarried males are:")
print(unmarried_males)

Married males are:
357
UnMarried males are:
130


In [103]:
#3
married_females=len(data.loc[((data['Married'] == 'Yes') & (data['Gender'] == 'Female'))])
print("Married Females are:")
print(married_females)
unmarried_females=len(data.loc[((data['Married'] == 'No') & (data['Gender'] == 'Female'))])
print("Unmarried Females are:")
print(unmarried_females)

Married Females are:
31
Unmarried Females are:
80


In [104]:
#4.
graduated_married_females=len(data.loc[((data['Married'] == 'Yes') & (data['Gender'] == 'Female') & (data['Education'] == 'Graduate'))])
print("graduated_married_females are :")
print(graduated_married_females)
graduated_unmarried_females=len(data.loc[((data['Married'] == 'No') & (data['Gender'] == 'Female') & (data['Education'] == 'Graduate'))])
print("graduated_unmarried_females are :")
print(graduated_unmarried_females)
nongraduated_married_females=len(data.loc[((data['Married'] == 'Yes') & (data['Gender'] == 'Female') & (data['Education'] == 'Not Graduate'))])
print("non_graduated_married_females are :")
print(nongraduated_married_females)
nongraduated_unmarried_females=len(data.loc[((data['Married'] == 'No') & (data['Gender'] == 'Female') & (data['Education'] == 'Not Graduate'))])
print("non_graduated_unmarried_females are :")
print(nongraduated_unmarried_females)

graduated_married_females are :
25
graduated_unmarried_females are :
66
non_graduated_married_females are :
6
non_graduated_unmarried_females are :
14


In [105]:
#5.Education column is encoded here with label encoding.Since there are 4 different values in "encoded" column so
#if we use one hot encoding then there might be issues with training the data as the columns increases.

In [106]:
#8.We will be considering all the necessary columns for the data training.The data columns that are used in the prediction of 
#the predicted value of the data class will be used that are relevant in making decision on the basis of the target class.
#Here in this dataset,every attribute will be taken into consideration for the prediction except for "Loan_ID" as "Loan_ID" 
#has no importance in the prediction if the loan will be granted to the customer or not.

In [107]:
#9
#Here I have prepared the model using KNN(K-Nearest Neighbour)
#I have chosen I KNN model because KNN is a classification technique to predict values of the target class.
#Since this was a prediction where the predicted value would vary between '0' and '1' or 'Yes' and 'No'.Classification
#technique would have been suited best for this model and I have tried between KNN and Logistic Regression and out of the 2 
#models KNN gives a better accuracy score.
#I have displayed all the regression techniques and it is found out that regression techniques show very low valued r2_scores.
#Thus KNN is selected

In [108]:
#10.No,I havent hyper paramiterizied the data

In [109]:
#11.
#KNN
from sklearn.neighbors import KNeighborsClassifier
knnClassifier=KNeighborsClassifier(n_neighbors=8)
knnClassifier.fit(x_train1,y_train1)
y_pred=knnClassifier.predict(x_test1)
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test1)

0.8108108108108109

In [110]:
#12
print("The accuracy of KNN classification is :")
print(accuracy_score(y_pred,y_test1))

The accuracy of KNN classification is :
0.8108108108108109


In [111]:
#13
#For a better model accuracy we can try more methods used for data cleaning,removing outliers.In this model the model is 
#encoded using label encoding,we can also try ONE-HOT ENCODING to see if it provides better results.
#We can manually change the attributes for each training techniques or use hyper paramitezation.

In [112]:
#14
#We can conclude that every column of the data might be necessary for the prediction of the data,but also it is not mandatory
#for every column to be included for the calculation.We can hereby note that every column for should be looked for missing data
#missing data should be taken care of,outliers should be looked after as welll and data should be encoded using proper 
#encoding techniques